### Promise 的主要使用

> 回调一直是javascript编程中比较令人纠结的写法，主要场景是用于处理“并行”或者“并列”的操作，然后在回调函数中处理操作结果。这样子原生的回调写法就会带来以下不便

- 回调结果状态不便管理
- 回调方式自由松散，没有规范约束

```js
// 原生回调方法

function func(num, callback) {
    setTimeout(() => {
        try {
            let result = 1/num
            callback(result, null)
        } catch(err) {
            callback(null, err)
        }
    }, 10)
}

func(1, (result, err) => {
    if(err) {
        console.log(err)
    } else {
        console.log(result)
    }
})
```

```js
// promise
function func1(num) {
    return new Promise((resolve) => {
        setTimeout(() => {
            let result = 1 / num
            resolve(result)
        }, 10)
    })
}

func1(2).then(result => {
    console.log(result)
}).catch(err => {
    console.log(err)
})
```

### Promise能力

> Promise带来的能力是任务管理，常用的方式有

`new Promise(...).then(onResolved, onRejected)`

- 任务管理
    - resolve成功状态，对应Promise.resolve
    - reject失败状态，对应Promise.reject
    - error异常状态，对应Promise.reject 或new Promise().catch(onReject)
- Thenabled机制提供任务方法链
    - new Promise().then().then().catch()


#### resolve

> 处理任务的成功状态

- 普通处理方式

```js
let p = new Promise((resolve, reject) => {
    setTimeout(() => {
        let result = 1
        resolve(result)
    }, 1000)
})
p.then(result => {
    console.log(result)
})
```

- 快捷方式

```js
let p = new Promise.resolve(1)
p.then(result => {
    console.log(result)
})
```

#### reject 

> 处理任务的失败状态

- 普通方式

```js
let p = new Promise((resolve, reject) => {
      setTimeout(() => {
        let result = 2;
         reject(result);
      }, 100)
    })
// 有两种方式获取失败状态
// 第一种，通过then 第二个函数参数处理失败状态
p.then((result)=>{ 
    console.log('success:',result);
}, (result)=>{ 
    console.log('fail:',result);
})
// "fail: 2"

// 第二种，或者通过，catch 获取失败状态
p.then((result)=>{ 
    console.log('success:',result);
}).catch((result)=>{ 
    console.log('error:',result);
})
// "error: 2"


// 注意：如果两种方式同时使用的话
// 只会被第一种方式reject操作失败的结果
p.then((result)=>{ 
    console.log('success:',result);
}, (result)=>{ 
    console.log('fail:',result);
}).catch((result)=>{ 
    console.log('error:',result);
})
// "fail: 2"
```